### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by francqz31** [Scarfmonster/HiFiPLN#2]
Hello Author ,
This is an amazing open source project especially for vocoders.
I was wondering if I can get the 78 hours dataset ? and if it is used in any training I would definitely cite you/the repo.

Thanks in advance!

**Comment by Scarfmonster** [comment]
The dataset has been contributed by various people, and I don't have the permission to redistribute it. There is a table with all contributors listed at https://utau.pl/hifipln/ if you ask them, maybe they'll be willing to share.
